### ISSUE TITLE
Liberland Git is now official!

### ISSUE THREAD

**Issue by burningtree** [liberland/Liberland#3]
A moment ago was president of Liberland Vit Jedlička officially approved existence GitHub account as a primary source for Liberland documents. We are currently working on the migration from existing infrastructure.

More information will follow.

**Comment by slush0** [comment]
It would be nice to have it confirmed by any official channel (website,
facebook, ...)
Dne 26. 4. 2015 12:55 "Jan Stránský" notifications@github.com napsal(a):

**Comment by michalspondr** [comment]
Is it a good idea to have **primary** source of documents on a third party website? :-)

**Comment by burningtree** [comment]
@slush0 Good point, it will happen later. In this moment still migrating.

@michalspondr **Git** is open protocol allow to move elsewhere without much difficulty. I expect in the future Git account will be hosted directly on Liberland infrastructure. In addition, GitHub has community, which is good for start.

**Comment by CrypticaScriptura** [comment]
Fantastic. :+1: Much more can be accomplished via git than say, a wiki.

**Comment by michalptacnik** [comment]
Thank you! Closing the issue for now, if you need any help, please reopen it!
