### ISSUE TITLE
Liberland transifex

### ISSUE THREAD

**Issue by lunokhod** [liberland/Liberland#5]
I just created a Liberland organization on Transifex: https://www.transifex.com/organization/liberland/dashboard. Transifex is useful for community based translation of documents, and is free for open source projects (as far as I can tell, everything on this git meets the definition of Open Source.).

I am willing to add anyone who is involved with this git as Administrator, so please just sign up and let me know. 

It is not clear to me how useful this will be, given that there are only two official languages in Liberland. Nevertheless, some documentation will eventually need to be translated in all languages. Please think about which documents these will be, and how the Transifex organization should be organized in projects and resources.

**Comment by michalptacnik** [comment]
There is likely no more access to the Transifex, and I don't seem to have a login. Closing this issue for now. If further help is needed or if that page still exists and is maintained, please let me know with the credentials!
