### ISSUE TITLE
How will we prevent Sybil Attacks on direct democracy?

### ISSUE THREAD

**Issue by JonathanMcCormickJr** [liberland/Liberland#7]
From what I understand from the Markdown docs, citizens will be issued Citizenship NFTs. How will we ensure that each person will have at most only 1 Citizenship NFT?

**Comment by JonathanMcCormickJr** [comment]
Maybe the KYC process for citizenship will prevent a person from creating multiple citizenship identities. However, in order for that to work, the KYC process needs to have at least one identifier that cannot be spoofed. Does any such identifier exist? 

Biometrics might work, but what would the tolerance level be before two different profiles are identified as a single individual? 

There are other ways of verifying identity, but a lot of them ultimately rely on trust. Any ideas?

**Comment by JonathanMcCormickJr** [comment]
More security concerns to consider regarding biometrics: https://www.iec.ch/blog/cyber-security-protecting-biometric-information

**Comment by vikivyas** [comment]
Collection of biometrics can not be possible now, as the collection centre and staffing of those centres are not in place.

I think KYC via web or mobile application, where one can do video KYC, other members verify it in (P2P) with the highly secured environment, such as Google Firebase etc. Using that UDI given by Firebase Authentication unique ID can help. Some image API scans take selfies and find duplicate persons will reduce workload for P2P.

**Comment by michalptacnik** [comment]
KYC prevents Sybil attacks to a large degree. There is a trust based element in citizenship and the rest of the chain is trustless. The validation etc. is done in the ways of all public blockchain, but the validators are citizens. The nominators, however, can come from the great crowd of non-KYCed users as well, to prevent the "inverse Sybil", where doxxed malicious actors could collude to influence/harm the system. Does this answer your question? If not, please, reopen the issue with a comment.
