### ISSUE TITLE
How will new LLM be issued to non-miners who volunteer for LL?

### ISSUE THREAD

**Issue by JonathanMcCormickJr** [liberland/Liberland#8]
As it stands, people can volunteer for Liberland in any number of state-approved ways and be compensated in LLM. Will this change once the blockchain is live? If so, what is our plan for incentivizing voluntary contributions of labor?

**Comment by michalptacnik** [comment]
No, this won't change. The volunteers will receive "Pooled LLM". Those who do really important jobs might receive unpooled ones, but this will be comparatively very rare. Does this answer your question?
